### ISSUE TITLE
Add validation feature

### ISSUE THREAD

**Issue by pont-us** [bcdev/nc2zarr#17]
It would be useful to have an output validation option for nc2zarr, along the lines of

`nc2zarr --config myconfig.yaml --validate`

which would go through the input files specified in the configuration and make sure, for each data value corresponding to a variable specified in the configuration, that a matching data value exists in the configured output Zarr.

This would of course be potentially very time-consuming for large datasets; `--structure-only` (just check that the structure's as expected) and `--sparse` (validate some small but representative subset of the data) may also be useful.

**Comment by forman** [comment]
I agree, this is very usefull, but I disagree with another handfull of CLI options. 

I suggest verifing that the output is readble through `xr.open_dataset(path, **open_kwargs)`. We can configure this in as a new top-level entry in the config. As a second step we later support assertions on the dataset content:

```yaml
verify:
  open_kwargs:
     engine: "zarr"
     decode_cf: true
  assertions:
     attrs:
        ...
     data_vars:
        ...
     coord_vars:
        ...        
```
