### ISSUE TITLE
Appending unnecessarily requires a coordinate variable

### ISSUE THREAD

**Issue by forman** [bcdev/nc2zarr#27]
With 

```yaml
input:
  paths: ...
  multi_file: false

output:
  path: ...
  append: true
  append_dim: "sounding_dim"
```

nc2zarr fails for existing dimension `"sounding_dim"` but missing (coordinate) variable `"sounding_dim"` with

    Error: Missing (coordinate) variable "sounding_dim" for dimension "sounding_dim".

However, appending datasets to existing Zarrs does not require a (coordinate) variable with same name.

The reason for this error is that `input/concat_dim`, if not given, is set to `output/append_dim` regardless of the value of `input/multi_file`.
